services:

  ansible:
    image: debiansshansible:12
    build: ./debiansshansible12
    volumes:
      - ./ansible:/home/srvadmin/ansible
      - ./artifacts:/mnt/artifacts

  debianssh11:
    image: debianssh:12
    build: ./debianssh12
    hostname: host5.localdomain
    ports:
      - ${SSH_PORT5:-27}:22

  debianssh12:
    image: debianssh:12
    build: ./debianssh12

  rockyssh9:
    image: rockyssh:9
    build: ./rockyssh9

  rockysshsystemd9:
    image: rockysshsystemd:9
    build: ./rockysshsystemd9
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw

  debiansshsystem12:
    image: debiansshsystemd:12
    build: ./debiansshsystemd12
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
