---
# vars file for roles/api
app_list:
  - app_port: 8082
    app_name: dummyapp
    app_binary: /mnt/artifacts/app.sh
    app_config: /mnt/artifacts/app.cfg
    app_user: john
    app_group: doe
    app_gid: 900
    app_uid: 900
  - app_port: 8080
    app_name: movieapi
    app_binary: /mnt/artifacts/movieapi-1.0.jar
    # app_config: null # to omit config 
    app_config: application.properties
    app_config_dir: bin/config
    app_user: renee
    app_group: moviefan
    app_gid: 901
    app_uid: 901
    app_notify: API

# JDBC URL (unique in this deployment)
# NB: work for postgresql, mysql, mariadb (possibility of adding extra vars)
app_jdbc_url: "jdbc:{{ db_vendor }}://{{ db_hostname }}:{{ db_port }}/{{ db_app_dbname }}"

app_show_sql: true
app_generate_ddl_auto: update