---
- name: Create Deployment User
  hosts: all
  become: yes
  tasks:
    - name: Create user
      ansible.builtin.user:
        name: deployuser
        shell: /usr/bin/bash
    - name: Add user in sudoers without password
      community.general.sudoers:
        name: deployuser
        user: deployuser
        commands: ALL
    - name: Copy SSH key
      ansible.posix.authorized_key:
        user: deployuser
        state: present
        key: "{{ lookup('file', '/home/srvadmin/.ssh/id_rsa_deploy.pub') }}"
        