---
- name: Install Database
  #hosts: db_*
  hosts: db_debian
  tags:
    - DB
  become: yes
  roles:
    - common
    - db
- name: Install API
  tags:
    - API
  hosts: api_rocky
  become: yes
  roles:
    - common
    - api