---
# tasks file for roles/api
- name: Intro role api
  ansible.builtin.debug:
    msg: "Begin role api"
    
- name: Create group
  ansible.builtin.group:
    name: "{{ app_group }}"
    gid: "{{ app_gid }}"

- name: Create user
  ansible.builtin.user:
    name: "{{ app_user }}"
    uid: "{{ app_uid }}"
    group: "{{ app_group }}"

- name: Prepare Filesystem
  ansible.builtin.file:
    path: /opt/{{ app_name }}/{{ item }}
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: '0750'
  loop:
    - bin
    - etc
    - log

- name: Copy api
  ansible.builtin.copy:
    src: /mnt/artifacts/app.sh
    dest: /opt/{{ app_name }}/bin
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: '0750'

- name: Copy config
  ansible.builtin.template:
    src: /mnt/artifacts/app.cfg.j2
    dest: /opt/{{ app_name }}/etc/app.cfg
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: '0640'

