---
# tasks file for roles/api
- name: Intro role api
  ansible.builtin.debug:
    msg: "Begin role api"

- import_tasks: package.yml
  tags: [PACKAGE]
    
- include_tasks: application.yml
  tags: [APPLICATION]
  vars:
    app_port: "{{ appli.app_port }}"
    app_name: "{{ appli.app_name }}"
    app_binary: "{{ appli.app_binary }}"
    app_config: "{{ appli.app_config }}"
    app_user: "{{ appli.app_user }}"
    app_group: "{{ appli.app_group }}"
    app_gid: "{{ appli.app_gid }}"
    app_uid: "{{ appli.app_uid }}"
  loop: "{{ app_list }}"
  loop_control:
    loop_var: appli


