---
- vars:
    app_name: "{{ app_list[1].app_name }}"
  block:

  - name: "Movie API service description"
    vars:
      app_binary: "{{ app_list[1].app_binary }}"
      app_user: "{{ app_list[1].app_user }}"
      app_dir: /opt/{{ app_name }}/bin
    ansible.builtin.template:
      src: springbootapp.service.j2
      dest: "/usr/lib/systemd/system/{{ app_name }}.service"
    notify: "Restart API"

  - name: "Enable API service"
    ansible.builtin.systemd_service:
      name: "{{ app_list[1].app_name }}"
      enabled: true
