---
# tasks file for roles/db
- name: Intro role db
  ansible.builtin.debug:
    msg: "Begin role db"

- import_tasks: package.yml
  tags:
    - PACKAGE

- import_tasks: service.yml
  tags:
    - SERVICE

- import_tasks: database.yml
  tags:
    - DATABASE
