---
# tasks file for roles/db
- name: Intro role db
  ansible.builtin.debug:
    msg: "Begin role db"

- name: Install Base Packages
  tags:
    - PACKAGE
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: 36000
  loop:
    - gpg
    - psmisc
    - net-tools
    - vim
    - tree

- name: Debug Ansible Facts and variables
  tags:
    - DEBUG
    - never
  vars:
    debug_var:
      info: "debug gathering facts"
      distribution_release: "{{ ansible_facts['distribution_release'] }}"
      distribution_release2: "{{ ansible_facts.distribution_release }}"
      distribution_release3: "{{ ansible_distribution_release }}"
      os_family: "{{ ansible_os_family }}"
      distribution: "{{ ansible_distribution }}"
      distribution_major_version: "{{ ansible_distribution_major_version | int }}"
  ansible.builtin.debug:
    #var: ansible_facts
    var: debug_var

  # https://www.postgresql.org/download/linux/debian/
    # add repo postgresql => check dir: /etc/apt/sources.list
    # add key repo postgresql
    # apt update (cache_valid_time:0) & install postgresql-[version]

- name: PostgreSQL Repository Key
  tags:
    - PACKAGE
  ansible.builtin.apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc

- name: PostgreSQL Repository
  tags:
    - PACKAGE
  ansible.builtin.apt_repository:
    repo: deb https://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main
    filename: postgresql

- name: PostgreSQL package
  tags:
    - PACKAGE
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 0 
    name: postgresql-{{ pg_version | default(16) }}